apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dynamo
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - argocd.argoproj.io/resources-finalizer
spec:
  project: default
  source:
    repoURL: https://helm.ngc.nvidia.com/nvidia/ai-dynamo
    chart: dynamo-platform
    targetRevision: 1.1.0-dev.1
    helm:
      releaseName: dynamo-platform
      valuesObject:
        global:
          grove:
            install: true
  destination:
    server: https://kubernetes.default.svc
    namespace: dynamo-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
